### ISSUE TITLE
Logo Telartes cuando has accedido

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/festivalesenred#13]
Una vez has accedido con tu cuenta el logo de Telartes te aparece en negro.
Debería aparecer a la derecha-arriba la posibilidad de "Cerrar sesión" además que "Admin Festivales" también debería aparecer en esa parte, a modo de menú de administración.

**Comment by jgenso** [comment]
este menu tiene que tener los menus de la cuenta del usuario: perfil, password, settings

**Comment by jgenso** [comment]
y en lugar de admin festivales, otra opcion de menu que diga festivales y muestre los festivales en formato tabla/lista con paginacion y un buscador por texto sencillo
