### ISSUE TITLE
index

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/festivalesenred#48]
El logo no está pegado a la izquierda de la pantalla.
![logo](https://cloud.githubusercontent.com/assets/7635775/8332048/b3713370-1a59-11e5-935b-88bc4787c75f.png)

Cuando hacemos click en una marca, la única forma de hacer que desaparezca es moviendo el mapa. Al pinchar fuera debería desaparecer el tooltip.
![festival_click](https://cloud.githubusercontent.com/assets/7635775/8332060/c3b8a934-1a59-11e5-86d1-ca0987533429.png)

En el apartado BUSCAR, tal vez sería mejor que apareciese arriba el botón. Cuando pinchamos en "Categorías" por ejemplo, se pierde el botón. Hay que reducir un poco el texto en "Categorías" y en Fechas no funcionan los calendarios. 
![buscar](https://cloud.githubusercontent.com/assets/7635775/8332073/de6ad77a-1a59-11e5-8f69-36462bc533eb.png)

**Comment by jgenso** [comment]
@marcelorodcla lo que este dentro de lo que puedas el resto lo hago yo

**Comment by danicotillas** [comment]
Por cierto, en el celular no aparece el menú. Esas 3 rayas que aparecen
arriba a la derecha

**Comment by marcelorodcla** [comment]
- Se arregló la posición del logo.

**Comment by marcelorodcla** [comment]
Menus responsive listos.
- Falta el calendario en el buscador
- Hay problemas jquery para plegar las opciones del buscador.
