### ISSUE TITLE
Que es

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/festivalesenred#49]
Colocar un poco de margin-right a la imagen para que el texto no esté tan pegada al texto.

La barra de abajo tal vez pueda quedar pegada al top-bottom?
![que_es](https://cloud.githubusercontent.com/assets/7635775/8332262/f852d7c2-1a5a-11e5-9bd9-5c5a5986d6f6.png)

Falta crear en el footer - Créditos con enlace a creditos.html que ya está arriba.

**Comment by danicotillas** [comment]
Mirar en el css para que onmouse over sea un naranja un poco más claro y no negro, porque se pierde en el fondo del footer.

**Comment by marcelorodcla** [comment]
Hecho

**Comment by jgenso** [comment]
Por si acaso si pones en tu commit fix #49 cierra el ticket automaticamente

2015-06-25 13:52 GMT-04:00 marcelorodcla notifications@github.com:

> Hecho
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hacklabcbba/festivalesenred/issues/49#issuecomment-115343607
> .

## 

*Juan Jose Olivera Rodriguez Genso Iniciativas Web +591.44505438 *
