### ISSUE TITLE
arreglar y terminar ver festival

### ISSUE THREAD

**Issue by jgenso** [hacklabcbba/festivalesenred#5]

**Comment by jgenso** [comment]
la informacion general esta, falta el mapa(otro ticket) y probablemente arreglos de pinta

**Comment by danicotillas** [comment]
No estoy pudiendo logearme con la cuenta de Twitter que es como tenía
configurado mi acceso. Además que en el mapa de inicio sigue mostrando el
nombre del espacio, no del festival cuando pinchas en el mapa.

2015-06-03 15:27 GMT-04:00 Juan Jose notifications@github.com:

**Comment by jgenso** [comment]
Ese es otro ticket, este es el de la pantalla de ver festival

El 3 de junio de 2015, 15:36, danicotillas notifications@github.com
escribió:

> No estoy pudiendo logearme con la cuenta de Twitter que es como tenía
> configurado mi acceso. Además que en el mapa de inicio sigue mostrando el
> nombre del espacio, no del festival cuando pinchas en el mapa.
> 
> 2015-06-03 15:27 GMT-04:00 Juan Jose notifications@github.com:
> 
> > la informacion general esta, falta el mapa(otro ticket) y probablemente
> > arreglos de pinta
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/hacklabcbba/festivalesenred/issues/5#issuecomment-108588095
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hacklabcbba/festivalesenred/issues/5#issuecomment-108590896
> .

## 

*Juan Jose Olivera Rodriguez Genso Iniciativas Web +591.44505438 *

**Comment by jgenso** [comment]
Ahora que veo no se puede ingresar al sitio via tiwtter

El 3 de junio de 2015, 15:46, Juan Jose Olivera juan@genso.com.bo
escribió:

> Ese es otro ticket, este es el de la pantalla de ver festival
> 
> El 3 de junio de 2015, 15:36, danicotillas notifications@github.com
> escribió:
> 
> > No estoy pudiendo logearme con la cuenta de Twitter que es como tenía
> > configurado mi acceso. Además que en el mapa de inicio sigue mostrando el
> > nombre del espacio, no del festival cuando pinchas en el mapa.
> > 
> > 2015-06-03 15:27 GMT-04:00 Juan Jose notifications@github.com:
> > 
> > > la informacion general esta, falta el mapa(otro ticket) y probablemente
> > > arreglos de pinta
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/hacklabcbba/festivalesenred/issues/5#issuecomment-108588095
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/hacklabcbba/festivalesenred/issues/5#issuecomment-108590896
> > .
> 
> ## 
> 
> *Juan Jose Olivera Rodriguez Genso Iniciativas Web +591.44505438
> <%2B591.44505438> *

## 

*Juan Jose Olivera Rodriguez Genso Iniciativas Web +591.44505438 *
