### ISSUE TITLE
Festivales

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/festivalesenred#50]
![festivales](https://cloud.githubusercontent.com/assets/7635775/8332514/400730e4-1a5c-11e5-8171-baf22b741d14.png)

**Comment by jgenso** [comment]
#43 lo de las redes sociales

**Comment by jgenso** [comment]
he cerrad este issue por que la descripcion ya se muestra completa, hay tickets abiertos para los otros dos puntos
