### ISSUE TITLE
Formulario

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/festivalesenred#55]
El campo de imágenes sólo nos vienen 3. Con los cambios que han hecho habría que añadir uno más.
Además en todos los campos aparece por defecto el logo de f.e.r.
El campo "Tags" aparece encima del encabezado "Imágenes"
![captura de pantalla 2015-06-25 16 11 29](https://cloud.githubusercontent.com/assets/7635775/8364561/3105cebc-1b55-11e5-9a6d-0153d2ace097.png)

Se siguen repitiendo las Redes. Habría que poner un texto por defecto en el campo para rellenar tipo "Si no aparece la Red que buscas, escríbela"
![captura de pantalla 2015-06-25 16 04 51](https://cloud.githubusercontent.com/assets/7635775/8364595/5f10f7b4-1b55-11e5-88a6-ba38844bfb1c.png)

Cuando queremos añadir otra Edición, el calendario no funciona. Me acabo de dar cuenta que este campo no se muestra en la info de Festivales, ¿o no lo encuentro?
![captura de pantalla 2015-06-25 16 04 14](https://cloud.githubusercontent.com/assets/7635775/8364616/8b160b56-1b55-11e5-9e91-d3f240fdaf0b.png)

**Comment by jgenso** [comment]
para lo de tags ya hay un ticket abierto para marcelo, para festivales anteriores tienes razon no mostramos esa info
